version: '3.8'

services:
  olecode-gateway-service:
    build:
      context: ./olecode-gateway-service
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    networks:
      - common-networks
    container_name: olecode-gateway-service

  olecode-user-service:
    build:
      context: ./olecode-user-service
      dockerfile: Dockerfile
    ports:
      - "8102:8102"
    networks:
      - common-networks
    depends_on:
      - olecode-gateway-service
    container_name: olecode-user-service

  olecode-question-service:
    build:
      context: ./olecode-question-service
      dockerfile: Dockerfile
    ports:
      - "8183:8183"
    networks:
      - common-networks
    depends_on:
      - olecode-user-service
    container_name: olecode-question-service

  yuoj-backend-judge-service:
    build:
      context: ./olecode-judge-service
      dockerfile: Dockerfile
    ports:
      - "8184:8184"
    networks:
      - common-networks
    depends_on:
      - olecode-user-service
      - olecode-gateway-service
    container_name: olecode-judge-service

networks:
  common-networks:
