# 公共配置文件
# @author ioomex
# @from <a href="https://github.com/yangwan-cw">yangwan-cw仓库</a>

spring:
  application:
    name: olecode-gateway-service

  # 默认 dev 环境
  profiles:
    active: dev

  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # session 配置
  session:
    # 取消注释开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/olecode
    username: root
    password: 9978@wzb

  main:
    web-application-type: reactive

  # Redis 配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000

  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: olecode-user-service
          uri: lb://olecode-user-service
          predicates:
            - Path=/api/user/**
        - id: olecode-question-service
          uri: lb://olecode-question-service
          predicates:
            - Path=/api/question/**
        - id: olecode-judge-service
          uri: lb://olecode-judge-service
          predicates:
            - Path=/api/judge/**

server:
  address: 0.0.0.0
  port: 8401
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        path: /api

knife4j:
  gateway:
    enabled: true
    discover:
      enabled: true
      strategy: discover
    version: swagger2

codesandbox:
  type: "remote"
